# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
    branches:
      development:
        - step:
           script:
             - git remote add sync https://github.com/iq-motion-control/json_clients.git
             - git checkout development
             - git pull
             - git push sync development
